// Delivery Fees
export const TAIWAN_ISLAND_DELIVERY_FEE_ID=1;
export const OUTLYING_ISLAND_DELIVERY_FEE_ID=2;
export const FREE_DELIVERY_ITEM_THRESHOLD_ID=3;
export const FREE_DELIVERY_PRICE_THRESHOLD_ID=4;

// Bonus Points
export const CASHBACK_RATE_ID=1;
export const REGISTER_BONUS_POINT_ID=2;
export const UPGRADE_TO_VIP_BONUS_POINT_ID=3;
export const UPGRADE_TO_SVIP_BONUS_POINT_ID=4;
